### ISSUE TITLE
curl_exec($this->handle) echoes HTTP response

### ISSUE THREAD

**Issue by mauriciabad** [Jhut89/Mailchimp-API-3.0-PHP#43]
## To Reproduce
```php
$api3 = new Mailchimp($apikey);
$reports = $api3->reports($cid)->unsubscribes()->get()->deserialize(true);
```

## Description
The request echoes this:
> string(17) "HTTP/1.1 200 OK " string(19) "Server: openresty " string(47) "Content-Type: application/json; charset=utf-8 " string(21) "Content-Length: 477 " string(23) "Vary: Accept-Encoding " string(52) ...

## Expected behavior
`$reports` contains only the deserialized content of the request body the without echoing anything.

## Where is this happening?
I think the problem is here
```php 
$this->setOption(CURLOPT_RETURNTRANSFER, true); // at MailchimpConnection.php line 112
```
OR
```php 
return curl_exec($this->handle); // at MailchimpConnection.php line 228 
```

## Additional comment
Maybe I'm doing something wrong 😅 .

**Comment by Jhut89** [comment]
hrmmm... Thats no good! 🚨 

I may have also may have inadvertently left some line output I was using to debug in there let me do a little digging and I'll will see whats up!

**Comment by Jhut89** [comment]
Ah yeah it looks like i left a `var_dump` in there.

https://github.com/Jhut89/Mailchimp-API-3.0-PHP/blob/master/src/Utilities/MailchimpConnection.php#L254

I'll get that removed later today.

**Comment by Jhut89** [comment]
I'm in the process of writing CI for this repo here:
https://github.com/Jhut89/Mailchimp-API-3.0-PHP-travis

 Part of which is a linter that should catch these kinds of things in the future! 🚀

**Comment by Jhut89** [comment]
Thanks for bringing this up! 

Foxed this in : #44
