### ISSUE TITLE
Array 'literal' syntax preventing PHP 5.3 compatibility

### ISSUE THREAD

**Issue by sfscs** [Jhut89/Mailchimp-API-3.0-PHP#5]
Hello, this package was listed as "php": ">=5.3.0" on packagist.org. However the use of the new array syntax introduced in php 5.4 is used extensively, preventing compatibility with 5.3.
```php
    public $req_post_prarams = [
        'operations'
    ];
```
Should be
```php
    public $req_post_prarams = array(
        'operations'
    );
```
But only if you want to keep php 5.3 compatibility, which I know is a hassle :) Regardless, as it is now the packagist php version requirement is incorrect, so you'd need to either bump the required version, or downgrade the array syntax to fix.

**Comment by Jhut89** [comment]
Ha! Good catch! I'm going to change the minimum required version. I'll close the issue once done.

Thanks again man!

**Comment by Jhut89** [comment]
Updated! :)
