### ISSUE TITLE
Saving tags

### ISSUE THREAD

**Issue by pks891618** [Jhut89/Mailchimp-API-3.0-PHP#55]
How can we add the tags to the subscribber while creating new subscriber 

	$post_params = [
    'EMAIL'=> $email_id,
    'FNAME'=>$customer_data->getData()['First_Name'],
    "LNAME"=>$customer_data->getData()['Last_Name'],
    "KLANTNAAM"=>,
    "KLANTNR"=>,
    "INDUSTRIE"=>,
    "TOER"=>,
    'status'=>'subscribed'
		];
Should i need to add tags as key in above array ?

$mailchimp
    ->lists(LIST_ID)
    ->members()
    ->post($post_params);

**Comment by Jhut89** [comment]
Hello!

Good question. As I understand it Mailchimp `tags` are actually `segments`
so to add a contact to a tag you would interact with Mailchimp's segments
API. Here is a link to the segments API documentation:
https://developer.mailchimp.com/documentation/mailchimp/reference/lists/segments/

Best wishes,
Hutch

**Comment by pks891618** [comment]
is it will work like this $mailchimp
    ->lists(LIST_ID)
    ->members()
    ->tags()
    ->post($tags);

**Comment by Jhut89** [comment]
Ah I think I understand what you are looking for. You would like to add a tag to a new contact in a POST to `lists/{list-id}/members`?

According to:
https://developer.mailchimp.com/documentation/mailchimp/reference/lists/members/#create-post_lists_list_id_members

It does appear that you should be able to:
```
$mailchimp
    ->lists(1234)
    ->members()
    ->post(
         // other params
         'tags' => [ // tag ids ] 
    )
```

and as you have indicated above you could also make a quick followup request to tag a subscriber using:
https://developer.mailchimp.com/documentation/mailchimp/reference/lists/members/tags/

I hope that helps out! 🏷 (tag) 😉

**Comment by pks891618** [comment]
$data=['tags'=>array("tag1")];
$mailchimp
    ->lists(LIST_ID)
    ->members("logistiek@mols.be")
    ->post(
         // other params
         $data
    );

sorry but its not working , its giving 405 errors

**Comment by pks891618** [comment]
ailchimpAPI\Responses\FailureResponse Object
(
    [headers:MailchimpAPI\Responses\MailchimpResponse:private] => Array
        (
            [Server] => openresty
            [Content-Type] => application/problem+json; charset=utf-8
            [Content-Length] => 305
            [X-Request-Id] => ac9dce7f-1b08-4176-b998-c049eb63de94
            [Link] => ; rel="describedBy"
            [Allow] => GET, DELETE, PATCH, PUT
            [Date] => Fri, 01 Feb 2019 19:05:42 GMT
            [Connection] => close
            [Set-Cookie] => _mcid=1.1a98298eb2e94a492ceac6db140e94fd; expires=Sat, 01-Feb-2020 19:05:42 GMT; Max-Age=31536000; path=/; domain=.mailchimp.com
        )

    [body:MailchimpAPI\Responses\MailchimpResponse:private] => {"type":"http://developer.mailchimp.com/documentation/mailchimp/guides/error-glossary/","title":"Method Not Allowed","status":405,"detail":"The requested method and resource are not compatible. See the Allow header for this resource's available methods.","instance":"ac9dce7f-1b08-4176-b998-c049eb63de94"}
    [http_code:MailchimpAPI\Responses\MailchimpResponse:private] => 405
)

**Comment by Jhut89** [comment]
I will go ahead and run a test once I get in front of my work machine to see if I can successfully hit that endpoint. For now though it's worth noting that the code you have above would put `'tags'=>array("tag1")` into its own array in the body params and the documentation makes it look like `tags` is a top level index within the body of the request.

**Comment by pks891618** [comment]
Thanks , i will really appericate if you can help me in checking  the actual function call to add the tags

**Comment by Jhut89** [comment]
Also in the most recent example you posted it looks like you are trying to hit an already existing subscriber. Which POSTing wouldn't be allowed to. Try calling the `put()` method instead.

**Comment by pks891618** [comment]
yes after trying to use the put following response 

MailchimpAPI\Responses\SuccessResponse Object
(
    [headers:MailchimpAPI\Responses\MailchimpResponse:private] => Array
        (
            [Server] => openresty
            [Content-Type] => application/json; charset=utf-8
            [Content-Length] => 2947
            [Vary] => Accept-Encoding
            [X-Request-Id] => 6ee7f45e-5df3-47ed-b026-aa6a2e09a809
            [Link] => ; rel="describedBy", ; rel="dashboard"
            [Date] => Fri, 01 Feb 2019 19:48:17 GMT
            [Connection] => keep-alive
            [Set-Cookie] => _mcid=1.eab47e854f54e5c2283ef319d0cd09fb; expires=Sat, 01-Feb-2020 19:48:17 GMT; Max-Age=31536000; path=/; domain=.mailchimp.com
        )

    [body:MailchimpAPI\Responses\MailchimpResponse:private] => {"id":"7a2965e2dcdb00418cdd6c8a804ebcb9","email_address":"logistiek@mols.be","unique_email_id":"01e1e66ee7","email_type":"html","status":"subscribed","merge_fields":{"FNAME":"TESSA","LNAME":"CLAES","ADDRESS":"","PHONE":"","TOER":"B - Bruin","KLANTNR":"MOLS","INDUSTRIE":"TRANSPORT","KLANTNAAM":"MOLS HUURWAGENS nv"},"stats":{"avg_open_rate":0,"avg_click_rate":0},"ip_signup":"","timestamp_signup":"","ip_opt":"","timestamp_opt":"2018-11-23T11:35:01+00:00","member_rating":2,"last_changed":"2019-02-01T19:48:17+00:00","language":"","vip":false,"email_client":"","location":{"latitude":0,"longitude":0,"gmtoff":0,"dstoff":0,"country_code":"","timezone":""},"tags_count":0,"tags":[],"list_id":"78225e5f30","_links":[{"rel":"self","href":"https://us12.api.mailchimp.com/3.0/lists/78225e5f30/members/7a2965e2dcdb00418cdd6c8a804ebcb9","method":"GET","targetSchema":"https://us12.api.mailchimp.com/schema/3.0/Definitions/Lists/Members/Response.json"},{"rel":"parent","href":"https://us12.api.mailchimp.com/3.0/lists/78225e5f30/members","method":"GET","targetSchema":"https://us12.api.mailchimp.com/schema/3.0/Definitions/Lists/Members/CollectionResponse.json","schema":"https://us12.api.mailchimp.com/schema/3.0/CollectionLinks/Lists/Members.json"},{"rel":"update","href":"https://us12.api.mailchimp.com/3.0/lists/78225e5f30/members/7a2965e2dcdb00418cdd6c8a804ebcb9","method":"PATCH","targetSchema":"https://us12.api.mailchimp.com/schema/3.0/Definitions/Lists/Members/Response.json","schema":"https://us12.api.mailchimp.com/schema/3.0/Definitions/Lists/Members/PATCH.json"},{"rel":"upsert","href":"https://us12.api.mailchimp.com/3.0/lists/78225e5f30/members/7a2965e2dcdb00418cdd6c8a804ebcb9","method":"PUT","targetSchema":"https://us12.api.mailchimp.com/schema/3.0/Definitions/Lists/Members/Response.json","schema":"https://us12.api.mailchimp.com/schema/3.0/Definitions/Lists/Members/PUT.json"},{"rel":"delete","href":"https://us12.api.mailchimp.com/3.0/lists/78225e5f30/members/7a2965e2dcdb00418cdd6c8a804ebcb9","method":"DELETE"},{"rel":"activity","href":"https://us12.api.mailchimp.com/3.0/lists/78225e5f30/members/7a2965e2dcdb00418cdd6c8a804ebcb9/activity","method":"GET","targetSchema":"https://us12.api.mailchimp.com/schema/3.0/Definitions/Lists/Members/Activity/Response.json"},{"rel":"goals","href":"https://us12.api.mailchimp.com/3.0/lists/78225e5f30/members/7a2965e2dcdb00418cdd6c8a804ebcb9/goals","method":"GET","targetSchema":"https://us12.api.mailchimp.com/schema/3.0/Definitions/Lists/Members/Goals/Response.json"},{"rel":"notes","href":"https://us12.api.mailchimp.com/3.0/lists/78225e5f30/members/7a2965e2dcdb00418cdd6c8a804ebcb9/notes","method":"GET","targetSchema":"https://us12.api.mailchimp.com/schema/3.0/Definitions/Lists/Members/Notes/CollectionResponse.json"},{"rel":"delete_permanent","href":"https://us12.api.mailchimp.com/3.0/lists/78225e5f30/members/7a2965e2dcdb00418cdd6c8a804ebcb9/actions/delete-permanent","method":"POST"}]}

**Comment by Jhut89** [comment]
Great! 🎉  It looks like it worked.

**Comment by pks891618** [comment]
[body:MailchimpAPI\Responses\MailchimpResponse:private] => {"id":"7a2965e2dcdb00418cdd6c8a804ebcb9","email_address":"logistiek@mols.be","unique_email_id":"01e1e66ee7","email_type":"html","status":"subscribed","merge_fields":{"FNAME":"TESSA","LNAME":"CLAES","ADDRESS":"","PHONE":"","TOER":"B - Bruin","KLANTNR":"MOLS","INDUSTRIE":"TRANSPORT","KLANTNAAM":"MOLS HUURWAGENS nv"},"stats":{"avg_open_rate":0,"avg_click_rate":0},"ip_signup":"","timestamp_signup":"","ip_opt":"","timestamp_opt":"2018-11-23T11:35:01+00:00","member_rating":2,"last_changed":"2019-02-01T19:48:17+00:00","language":"","vip":false,"email_client":"","location":{"latitude":0,"longitude":0,"gmtoff":0,"dstoff":0,"country_code":"","timezone":""},"tags_count":0,"tags":[],"list_id":"78225e5f30","_links":[{"rel":"self","href":"https://us12.api.mailchimp.com/3.0/lists/78225e5f30/members/7a2965e2dcdb00418cdd6c8a804ebcb9","method":"GET","targetSchema":"https://us12.api.mailchimp.com/schema/3.0/Definitions/Lists/Members/Response.json"},{"rel":"parent","href":"https://us12.api.mailchimp.com/3.0/lists/78225e5f30/members","method":"GET","targetSchema":"https://us12.api.mailchimp.com/schema/3.0/Definitions/Lists/Members/CollectionResponse.json","schema":"https://us12.api.mailchimp.com/schema/3.0/CollectionLinks/Lists/Members.json"},{"rel":"update","href":"https://us12.api.mailchimp.com/3.0/lists/78225e5f30/members/7a2965e2dcdb00418cdd6c8a804ebcb9","method":"PATCH","targetSchema":"https://us12.api.mailchimp.com/schema/3.0/Definitions/Lists/Members/Response.json","schema":"https://us12.api.mailchimp.com/schema/3.0/Definitions/Lists/Members/PATCH.json"},{"rel":"upsert","href":"https://us12.api.mailchimp.com/3.0/lists/78225e5f30/members/7a2965e2dcdb00418cdd6c8a804ebcb9","method":"PUT","targetSchema":"https://us12.api.mailchimp.com/schema/3.0/Definitions/Lists/Members/Response.json","schema":"https://us12.api.mailchimp.com/schema/3.0/Definitions/Lists/Members/PUT.json"},{"rel":"delete","href":"https://us12.api.mailchimp.com/3.0/lists/78225e5f30/members/7a2965e2dcdb00418cdd6c8a804ebcb9","method":"DELETE"},{"rel":"activity","href":"https://us12.api.mailchimp.com/3.0/lists/78225e5f30/members/7a2965e2dcdb00418cdd6c8a804ebcb9/activity","method":"GET","targetSchema":"https://us12.api.mailchimp.com/schema/3.0/Definitions/Lists/Members/Activity/Response.json"},{"rel":"goals","href":"https://us12.api.mailchimp.com/3.0/lists/78225e5f30/members/7a2965e2dcdb00418cdd6c8a804ebcb9/goals","method":"GET","targetSchema":"https://us12.api.mailchimp.com/schema/3.0/Definitions/Lists/Members/Goals/Response.json"},{"rel":"notes","href":"https://us12.api.mailchimp.com/3.0/lists/78225e5f30/members/7a2965e2dcdb00418cdd6c8a804ebcb9/notes","method":"GET","targetSchema":"https://us12.api.mailchimp.com/schema/3.0/Definitions/Lists/Members/Notes/CollectionResponse.json"},{"rel":"delete_permanent","href":"https://us12.api.mailchimp.com/3.0/lists/78225e5f30/members/7a2965e2dcdb00418cdd6c8a804ebcb9/actions/delete-permanent","method":"POST"}]}
sorry but it dont add the tags

**Comment by Jhut89** [comment]
Ok cool I'll have to check this out once I'm in front of my machine.

**Comment by pks891618** [comment]
sure , no problem .thanks for the help

**Comment by Jhut89** [comment]
Hello! I finally got home to my computer and here is what I found.I was sucessful in tagging a subscriber using this endpoint with the following code:
https://developer.mailchimp.com/documentation/mailchimp/reference/lists/members/tags/

```php
$mailchimp
    ->lists('1a2b3c4d')
    ->members('000128278@mailchimp.com')
    ->tags()
    ->post([
        'tags' => [
            [
                'name' => 'tag1',
                'status' => 'active'
            ]
        ]
    ]);
```
I was also successfully able to post a new contact with a tag by doing:
```php
$mailchimp
    ->lists('1a2b3c4d')
    ->members()
    ->post([
        'email_address' => '01234567890@mailchimp.com',
        'status' => 'subscribed',
        'tags' => [
            'tag2'
        ]
    ]);
```
I tried to PUT tags to an existing subscriber but found it doesn't look like tag have been implemented for:
https://developer.mailchimp.com/documentation/mailchimp/reference/lists/members/#edit-patch_lists_list_id_members_subscriber_hash

**Comment by pks891618** [comment]
great  it works

**Comment by Jhut89** [comment]
I have'nt found a way to do that yet. For now it looks like Mailchimp will require you to get all the existing tags on a contact and then post with those plus the new ones.

**Comment by pks891618** [comment]
When we are trying to add new then existing tag remains there , 
basically i want to update the existing tag , the new tag must overwrite the existing . 
e.g if a contact have "city" tag then if we want to add the new tag country and state then the final tag will be state and country , city need to be overwrite with the new once
