### ISSUE TITLE
Unable to deserialize response

### ISSUE THREAD

**Issue by rhsumon** [Jhut89/Mailchimp-API-3.0-PHP#56]
**Describe the bug**
When trying to call Mailchimp::oauthExchange it always shows the exception `Unable to deserialize response`

**Expected behavior**
It should return the apiKey

**Additional context**
I checked the code and tried printed out the response and got the body correct but in the file Mailchimp.php (304) line produces the exception, though on deserialize method i tried printing the body and decoded data which prints well

**Comment by Jhut89** [comment]
I am unable to replicate this behavior, everything seems to work as expected for me. 🤔 Can you post the output of `var_dump($this->body)` in `MailchimpResponse::deserialize()`?

**Comment by rhsumon** [comment]
Let's close the issue, it's all about the 30 sec issue. Because the code expires in 30 seconds and while I tried it took more than 30 secs because of my environment. Thanks btw for your reply, and thanks for the great piece of work.

**Comment by Jhut89** [comment]
No worries let me know if I can still help in any way!

**Comment by umarm6** [comment]
i am having same issue
