### ISSUE TITLE
Not response

### ISSUE THREAD

**Issue by Kukulkan2012** [Jhut89/Mailchimp-API-3.0-PHP#57]
After the request is not response

1. Include the https://github.com/Jhut89/Mailchimp-API-3.0-PHP#post library.
2. Then I execute the query (new Mailchimp ($ this-> secretKey)) -> lists ($ this-> listId) -> members () -> post ($ post_params);
other methods don't return anything either
3. $ post_params = ['email_address' => $ email, 'status' => 'pending', 'merge_fields' => ['FNAME' => $ this-> user-> name,]];

I expected to see the answer as described here.
https://github.com/Jhut89/Mailchimp-API-3.0-PHP/wiki/Post-Requests
![2019-02-19 16-45-59](https://user-images.githubusercontent.com/18314855/53019528-fea3ce00-3465-11e9-927f-7f07a539ba54.png)

**Comment by Jhut89** [comment]
Hmm, I'm able to get a response. Have you deserialized you response, like in this article? 
https://github.com/Jhut89/Mailchimp-API-3.0-PHP/wiki/Handling-A-Response

What do you see when you var_dump the results of your request?

**Comment by Kukulkan2012** [comment]
Hello, I figured it out yesterday. You're right, you need to use additional methods after the post (), get (), etc. methods. In your documentation, this is not explicitly described, if not difficult, can you add these items to the description? For example on the page
 https://github.com/Jhut89/Mailchimp-API-3.0-PHP/wiki/Post-Requests
I immediately sent the answer to the browser, and an empty object came to me. I did not immediately find the information in the documentation. So that in the future people will not be confused, please correct the documentation, just mark that the response does not come by default, but you need to use getters, or deserialize (). I consider the question closed.

**Comment by Jhut89** [comment]
Ok, thanks for the follow up.
