### ISSUE TITLE
Passing language to the subscribed user

### ISSUE THREAD

**Issue by pks891618** [Jhut89/Mailchimp-API-3.0-PHP#58]
How can we send  the language for the particular subscribed user ?

**Comment by Jhut89** [comment]
According to the Mailchimp API documentation here you should be able to set
th ‘language’ index in a request to /lists/{list-ID}/members.

See the documentation here:
https://developer.mailchimp.com/documentation/mailchimp/reference/lists/members/

**Comment by pks891618** [comment]
I am trying to set the language but its not working

$post_params = [
   "merge_fields" => [
    'FNAME'=>$customer_data->getData()['First_Name'],
    "LNAME"=>$customer_data->getData()['Last_Name'],
    "KLANTNAAM"=>$account_data->getData()['Account_Name'],
    "KLANTNR"=>$account_data->getData()['Klantnummer'],
    "INDUSTRIE"=>$account_data->getData()['Industry'],
    "TOER"=>$account_data->getData()['Toer'],
    "tags"=>$tags,
    "language"=>"nl",
    'status'=>'subscribed',

		]
	];

//post /patch data to the mailchimp and subscribe to the data			
$mailchimp
	->lists(LIST_toer)
	->members($email_id)
	->put($post_params)->deserialize();

**Comment by Jhut89** [comment]
It looks like, language is nested in the merge fields above and in the documentation its a top level param. I have been on vacation but will try setting the language for a subscriber in my test account when I get home.

**Comment by Jhut89** [comment]
Hey there! 👋

I was able to successfully able to set the language of a subscriber using the following code:
```php
$mailchimp
    ->lists('1a2b3c4d')
    ->members('0001@mailchimp.com')
    ->put([
        'email_address' => '0001@mailchimp.com',
        'status' => 'subscribed',
        'language' => 'en'
    ]);
```

**Comment by Jhut89** [comment]
I think perhaps the problem you are seeing is that you have nested the `language` index into your merge fields.

**Comment by Jhut89** [comment]
I'm going to go ahead and close this issue out, but please let me know if are still having difficulties. 😃

**Comment by pks891618** [comment]
Sorry for late response was busy with some work

"merge_fields" => [
'FNAME'=>$customer_data->getData()['First_Name'],
"LNAME"=>$customer_data->getData()['Last_Name'],
"KLANTNAAM"=>$account_data->getData()['Account_Name'],
"KLANTNR"=>$account_data->getData()['Klantnummer'],
"INDUSTRIE"=>$account_data->getData()['Industry'],
"TOER"=>$account_data->getData()['Toer'],
"tags"=>$tags,
"language"=>"nl",
'status'=>'subscribed',

	]
];
//post /patch data to the mailchimp and subscribe to the data
$mailchimp
->lists(LIST_toer)
->members($email_id)
->put($post_params)->deserialize();


what need to be changed in this code for updating the language ?

**Comment by Jhut89** [comment]
Sure thing. Currently your code looks like this:
```
$post_params = [
            "merge_fields" => [
                'FNAME'=>$customer_data->getData()['First_Name'],
                "LNAME"=>$customer_data->getData()['Last_Name'],
                "KLANTNAAM"=>$account_data->getData()['Account_Name'],
                "KLANTNR"=>$account_data->getData()['Klantnummer'],
                "INDUSTRIE"=>$account_data->getData()['Industry'],
                "TOER"=>$account_data->getData()['Toer'],
                "tags"=>$tags,
                "language"=>"nl",
                'status'=>'subscribed',
            ]
        ];
```
You can see the `language`, `status` and `tags` indexes are nested inside of `merge_fields`. They need to be their own top level index like this:
```
$post_params = [
            "merge_fields" => [
                'FNAME'=>$customer_data->getData()['First_Name'],
                "LNAME"=>$customer_data->getData()['Last_Name'],
                "KLANTNAAM"=>$account_data->getData()['Account_Name'],
                "KLANTNR"=>$account_data->getData()['Klantnummer'],
                "INDUSTRIE"=>$account_data->getData()['Industry'],
                "TOER"=>$account_data->getData()['Toer']
            ],
            "language"=>"nl",
            "status"=>"subscribed",
            "tags"=>$tags
        ];
```
Also don't forget that the `email_address` is required.
