### ISSUE TITLE
Getting error "The curl request failed: error:02001018:system library:fopen:Too many open files"

### ISSUE THREAD

**Issue by LeftPinkie** [Jhut89/Mailchimp-API-3.0-PHP#67]
I am getting the error "The curl request failed: error:02001018:system library:fopen:Too many open files" when deleting many subscribers (1000+).  I am currently iterating my current subscribers and then issuing the delete().  Is there something I can do to clear / close the curl handles as I finish each iteration?

**Comment by Jhut89** [comment]
Hey!

It looks like at some point during development we forgot to call ‘close()’
on each MailchimpConnection during ‘execute()’ I will update the library
once I am in front of my computer, and put up a new release once done.

Thanks!
Hutch

**Comment by Jhut89** [comment]
PR for fix here: https://github.com/Jhut89/Mailchimp-API-3.0-PHP/pull/68

**Comment by Jhut89** [comment]
You should be good to go. You can pull the fix by updating to `3.1.3`.

**Comment by LeftPinkie** [comment]
Thank you.

**Comment by Jhut89** [comment]
No problem, feel free to open another issue should you see anything else.
