### ISSUE TITLE
Setting the user-agent

### ISSUE THREAD

**Issue by leereichardt** [Jhut89/Mailchimp-API-3.0-PHP#69]
Is it possible to set the user agent string when using this wrapper? This is encouraged by Mailchimp so they can identify our integration in their logs.

Thanks in advance!

**Comment by Jhut89** [comment]
Currently the user agent string is set in the `MailchimpConnection` class when preparing the file handler. You right, having that set is helpful to troubleshoot issues when communicating with Mailchimp support, as well it allows Mailchimp to keep metrics around use of this library. That is why we chose to include this repositories URL in the user agent string. I'm hesitant to remove that or allow it to be altered easily when using versions of this library, as we might loose those benefits.

That said if you are looking to alter that user agent string when calling Mailchimp's API through this library you could fork this repository and make edits in your fork.

**Comment by leereichardt** [comment]
But the user is losing the benefits of troubleshooting their specific connection with Mailchimp. How are those metrics more important than that? I feel like this should really be a user set attribute, should it not?

**Comment by leereichardt** [comment]
Apologies. I had another comment, but it came across snarky so I deleted it. It's early in the morning and I'm still sleepy

**Comment by Jhut89** [comment]
😄 No worries, I know how that goes. Since I wrote that last response I did have the thought that we could add a function that appends to the user agent string after a delimiter like a `;`. That way string matching can be done for both on the Mailchimp end.

**Comment by leereichardt** [comment]
That would be helpful. You could possibly look at having a second parameter in the constructor to pass through additional options?

**Comment by leereichardt** [comment]
Hi @Jhut89, any progress on this? Or any final ideas on how you'd like to achieve this? I could "try" do a PR for it?

**Comment by Jhut89** [comment]
Hey!

So sorry it’s taken a while! Work got busy. 😆I have some time off later
this week for a holiday and will likely be able to add this then.

If you want to give it a try please feel free! No pressure though.  I don’t
want to be super prescriptive about how to make it happen, but I would ask
we limit it to additive changes.

Best wishes,
Hutch

**Comment by leereichardt** [comment]
Hi @Jhut89!

Created a PR for you now. The changes are pretty minor so hopefully, you're happy with the implementation.

Lee

**Comment by Jhut89** [comment]
Just to catch anyone up reading this thread, we resolved this in #70
