### ISSUE TITLE
Namespaces

### ISSUE THREAD

**Issue by damianua** [Jhut89/Mailchimp-API-3.0-PHP#7]
Hey, first for all thx for your library. Can you add namespaces to your classes? Cuz class name "Lists", for example, its very common name, which use in many legacy projects.

**Comment by Jhut89** [comment]
Thanks for the suggestion. I will look into Implementing Namespaces as soon as I get an opportunity to do so.

**Comment by Jhut89** [comment]
@damianua I'm looking at implementing an autoloading friendly version here: https://github.com/Jhut89/Mailchimp-API-3.0-PHP/tree/AutoLoading/NameSpacing

**Comment by Jhut89** [comment]
I will likely PR this against master at some point in the near future.

**Comment by Jhut89** [comment]
Addressed in `3.0.0`
