### ISSUE TITLE
List->Members->Events

### ISSUE THREAD

**Issue by centraleffects** [Jhut89/Mailchimp-API-3.0-PHP#76]
This feature is missing https://mailchimp.com/developer/reference/lists/list-members/list-member-events/

Should be able to do: 
`$mailchimp
    ->lists('1a2b3c4d')
    ->members('a1167f5be2df7113beb69c95ebcdb2fd')
   ->events(['name' => 'your_event_name'])`

**Comment by centraleffects** [comment]
@Jhut89  Thanks. I  Added pull request #77 to address this.

**Comment by Jhut89** [comment]
👏 👏 👏

**Comment by Jhut89** [comment]
You should be good. Your PR is merged and a minor release was made once unit tests passed. You should be able to pull the update library through composer version `3.2.1`

**Comment by centraleffects** [comment]
Great. Thank you.
