### ISSUE TITLE
does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. 

### ISSUE THREAD

**Issue by lechbaczynski** [Jhut89/Mailchimp-API-3.0-PHP#78]
**Describe the bug**

using composer, I get the notices:

Deprecation Notice: Class MailchimpTests\Resources\Automations\EmailsTest located in ./vendor/jhut89/mailchimp3php/tests/Automations/EmailsTest.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0

The same for classes:

MailchimpTests\Resources\Automations\Emails\QueueTest located in ./vendor/jhut89/mailchimp3php/tests/Automations/Emails/QueueTest.php  

MailchimpTests\Resources\Automations\RemovedSubscribersTest located in ./vendor/jhut89/mailchimp3php/tests/Automations/RemovedSubscribersTest.php 

**To Reproduce**
1. in composer.json  :      "jhut89/mailchimp3php": "^3.1",
(in composer.lock the version is now:
           "name": "jhut89/mailchimp3php",
            "version": "3.2.1",
2. composer update/install

**Expected behavior**
no warnings

**Additional context**

composer version 1.10.5

**Comment by Jhut89** [comment]
I'll try and take a look at this this weekend. Feel free to take a look on your own and PR if you believe you have a fix.

**Comment by Jhut89** [comment]
Addressing this in: https://github.com/Jhut89/Mailchimp-API-3.0-PHP/pull/79. I'll make a minor release once merged.

**Comment by Jhut89** [comment]
Updating to `3.2.2` should remove those warnings. Please let me know if it persists.
