### ISSUE TITLE
Typo in Wiki: Method $response->wasSuccessful() is incorrect 

### ISSUE THREAD

**Issue by banakito** [Jhut89/Mailchimp-API-3.0-PHP#80]
Minor bug in wiki: 

`$response->wasSuccessful() // returns true if the http code is in the 200 range`

**To Reproduce**
Just visit the wiki in `Handling a Response` Section

**Expected behavior**
Text must be:

`$response->wasSuccess() // returns true if the http code is in the 200 range`

**Comment by Jhut89** [comment]
Whoops, sorry for the typo. It should be all good now.
